[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
cross_bridge = "28MEkUJbffntPxM2WFu6mSaKnomnsPg1KHWgCKLukGNb"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/shooter/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
